menu:
  GitHub: https://github.com/YanWQ-monad
  About: /about

# Analytics
gtm: GTM-PP344KH

# Copyright Infomation
startyear: 2017

# 3rd resources
resources:
  js:
    - /js/all.min.js
  css:
    - /css/all.min.css
