on:
  push:
    branches:
    - blog

name: Build and deploy on push

jobs:
  deployHexo:
    name: DeployHexoBlog
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'
    - name: use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '14.x'
    - run: npm install
    - name: hexo generate
      uses: ./.github/generate
    - name: hexo deploy
      run: |
        npm install --save hexo-deployer-git
        sed -i "s/{GITHUB_TOKEN}/${GITHUB_TOKEN}/g" _config.yml
        npx hexo deploy
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
